### PR TITLE
Snhut 2776 create upload or add experience details page

### PR DESCRIPTION
**Pull request by mikiasmh**
### Description

- Add redirection from the prior-experiences main page to the create page with the click of buttons.

#### Videos

https://user-images.githubusercontent.com/97548296/221900099-44f4a84f-db02-4dfb-b43b-62625b4d0e31.mov

#### Screenshots

Screenshot 2023-02-28 at 9 54 29 AM
Screenshot 2023-02-28 at 9 54 22 AM

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2776)

### CODE REVIEW

**Comment by dmitriy-rodimin-sada** [comment]
@mikiasmh Can you write more explanations. I watched video few times but not exactly following the flow.
One area of concern about the code itself is the extensive overriding of the according component styles. I wonder about how  maintainable this approach is and wether things can break if the accordion is modifies in the Design System. If such as extensive overriding is needed, I would say it might be better to create another component in the Design System.

**Review by dmitriy-rodimin-sada — COMMENTED** [review]
@mikiasmh Can you write more explanations. I watched video few times but not exactly following the flow.
One area of concern about the code itself is the extensive overriding of the according component styles. I wonder about how maintainable this approach is and wether things can break if the accordion is modifies in the Design System. If such as extensive overriding is needed, I would say it might be better to create another component in the Design System.

**Comment by mikiasmh** [comment]
> @mikiasmh Can you write more explanations. I watched video few times but not exactly following the flow. One area of concern about the code itself is the extensive overriding of the according component styles. I wonder about how maintainable this approach is and wether things can break if the accordion is modifies in the Design System. If such as extensive overriding is needed, I would say it might be better to create another component in the Design System.

@dmitriy-rodimin-sada this particular PR is concerned with redirecting the user from the prior-experiences (main) page to the create page when the user clicks either the " Upload or add experience(s) manually " button or the " Upload or add experience details " card inside the accordion. The Accordion itself was integrated in the prior-experiences page a while ago. The reason for the overrides is because the existing Accordion component is not flexible enough to let us pass different style options. This is something I can convey to the PLA team. But for this particular PR, the goal is redirecting the user to the create page.

**Comment by dmitriy-rodimin-sada** [comment]
Thanks for clarifying the flow. I was confused where you go back in the video but now understand that you were trying to access create from the expandable panel.

For the accordion implementation I remain with in my opinion that in this case using gp-accordion is not the best option, 
styling is significantly different requiring deep re-theming. I am OK with this being one-off case, if this pattern is repeating, need to rethink approach and refactor.

**Comment by mikiasmh** [comment]
> Thanks for clarifying the flow. I was confused where you go back in the video but now understand that you were trying to access create from the expandable panel.
> 
> For the accordion implementation I remain with in my opinion that in this case using gp-accordion is not the best option, styling is significantly different requiring deep re-theming. I am OK with this being one-off case, if this pattern is repeating, need to rethink approach and refactor.

Ok, thanks Dmitriy. I need approval to merge.

**Review by dmitriy-rodimin-sada — APPROVED** [review]

**Pull request merged**
