### PR TITLE
SNHUT 3223 - discipline association group details CRUD 

### PR DESCRIPTION
**Pull request by hilal-sadaindia**
### Description

SNHUT 3223 - discipline association group details CRUD and users listing page

#### Video
[3223.webm](https://user-images.githubusercontent.com/118151666/225959693-b3013c25-7b8f-46fa-8d73-b09f2b8a87f2.webm)

[3223-1.webm](https://user-images.githubusercontent.com/118151666/225959822-9a75e386-f0a0-44a8-8818-03dcd5fad0fa.webm)

#### Screenshots

| Original | Updated |
| -------- | ------- |
|          |         |
Screenshot 2023-03-08 at 7 21 44 AM
Screenshot 2023-03-08 at 7 21 48 AM

Screenshot 2023-03-08 at 7 22 02 AM
Screenshot 2023-03-08 at 7 22 10 AM

### Other Details

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-3223)

#### Checklist

- [x] **Assumptions of User Story met (including acceptance criteria)**
- [x] **All new necessary Unit tests were CREATED** to promote code coverage
- [x] **All required unit tests are PASSING**
- [x] The proposed functionality was tested manually locally, and it's working fine.
- [x] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [x] Unnecessary console.logs AND/OR comments were removed
- [x] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [x] Ensure configuration and/or build changes documented

### CODE REVIEW

**Comment by sada-ajith** [comment]
Unit tests are failing 

` FAIL   toboggan-app  apps/toboggan-app/src/app/association-group/components/discipline-list/discipline-list.component.spec.ts
  ● Test suite failed to run

    apps/toboggan-app/src/app/association-group/components/discipline-list/discipline-list.component.spec.ts:89:32 - error TS2345: Argument of type '{ discipline: string; uuid: string; status: string; groupId: string; }' is not assignable to parameter of type 'IDiscipline'.
      Type '{ discipline: string; uuid: string; status: string; groupId: string; }' is missing the following properties from type 'IDiscipline': name, displayName

    89     component.removeDiscipline(discipline);
                                      ~~~~~~~~~~

 FAIL   toboggan-app  apps/toboggan-app/src/app/association-group/components/add-new-discipline/add-new-discipline.component.spec.ts
  ● Test suite failed to run

    apps/toboggan-app/src/app/association-group/components/add-new-discipline/add-new-discipline.component.spec.ts:55:52 - error TS2769: No overload matches this call.
      Overload 1 of 4, '(object: AddNewDisciplineComponent, method: FunctionPropertyNames<Required<AddNewDisciplineComponent>>): SpyInstance<...>', gave the following error.
        Argument of type '"getDiscipline"' is not assignable to parameter of type 'FunctionPropertyNames<Required<AddNewDisciplineComponent>>'.
      Overload 2 of 4, '(object: AddNewDisciplineComponent, method: "addDisciplineToGroupAction"): SpyInstance<EventEmitter<boolean | undefined>, [isAsync?: boolean | undefined]>', gave the following error.
        Argument of type '"getDiscipline"' is not assignable to parameter of type '"addDisciplineToGroupAction"'.

    55     const getDisciplineSpy = jest.spyOn(component, 'getDiscipline');
                                                          ~~~~~~~~~~~~~~~

    apps/toboggan-app/src/app/association-group/components/add-new-discipline/add-new-discipline.component.spec.ts:93:5 - error TS2322: Type 'string[]' is not assignable to type 'IDiscipline[]'.
      Type 'string' is not assignable to type 'IDiscipline'.

    93     component.disciplines = mockDisciplines;
`

**Review by sada-ajith — CHANGES_REQUESTED** [review]
Please fix unit tests, before raising PR

**Comment by hilal-sadaindia** [comment]
> Please fix unit tests, before raising PR

Updated with unit test issue solved

**Comment by sada-ajith** [comment]
While creating discipline group , 422 validation error is thrown 
No error message is shown. PLease investigate

Screenshot 2023-03-15 at 10 16 37 AM
Screenshot 2023-03-15 at 10 16 31 AM

**Comment by sada-ajith** [comment]
After adding discipline to the group, table is refreshed

**Comment by sada-ajith** [comment]
Screenshot 2023-03-15 at 10 25 24 AM

**Comment by hilal-sadaindia** [comment]
Screenshot 2023-03-15 at 4 27 23 PM

Screenshot 2023-03-15 at 4 27 20 PM

**Comment by hilal-sadaindia** [comment]
> Screenshot 2023-03-15 at 10 25 24 AM

**Comment by sada-ajith** [comment]
Screenshot 2023-03-15 at 10 51 57 PM

**Comment by sada-ajith** [comment]
multiple calls are getting triggered for fetching group details
Screenshot 2023-03-15 at 10 46 23 PM

**Comment by sada-ajith** [comment]
Search / filter and sort should not trigger api calls
Please check implementation in `microservices/turbine-admin/apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts`

change minimum height of table to 500px

**Comment by sada-ajith** [comment]
Update group is also failing

**Comment by hilal-sadaindia** [comment]
> Screenshot 2023-03-15 at 10 51 57 PM

its actually working for me.

**Review by sada-ajith — APPROVED** [review]

**Pull request merged**
