### PR TITLE
Upload SRL Zip File Integration

### PR DESCRIPTION
**Pull request by Mubashir-sadaindia**
### Description

- Integrate uploading of SRL file integration
    (how it is handled  - if file name starts with SRL - it will be uploading as SRL file or else normal Madcap upload)

- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-4528)

#### Checklist

- [x] **Assumptions of User Story met (including acceptance criteria)**
- [x] **All new necessary Unit tests were CREATED** to promote code coverage
- [x] **All required unit tests are PASSING**
- [x] The proposed functionality was tested manually locally, and it's working fine.
- [x] PR was properly reviewed by a team member (at least 1 approval required to merge!)
- [x] Unnecessary console.logs AND/OR comments were removed
- [ ] Feature ok-ed by UX designer (If needed - not for back end components) and Product Owner
- [ ] Ensure configuration and/or build changes documented

### CODE REVIEW

**Review by mk-sada — APPROVED** [review]
Can't really test this one. Approve and merging for now.

**Review by mk-sada — CHANGES_REQUESTED** [review]
Unit tests are failing. Function signature mismatch. Fix please.

```
FAIL src/app/content-management/services/content-upload.service.spec.ts
  ● Test suite failed to run

    apps/toboggan-app/src/app/content-management/services/content-upload.service.spec.ts:88:15 - error TS2554: Expected 3 arguments, but got 2.

    88       service.uploadMadCapFile(uuid, file).subscribe((res) => {
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      apps/toboggan-app/src/app/content-management/services/content-upload.service.ts:47:50
        47   uploadMadCapFile(uuid: string, isSrl: boolean, content_file: FormData) {
                                                            ~~~~~~~~~~~~~~~~~~~~~~
        An argument for 'content_file' was not provided.
```

**Comment by Mubashir-sadaindia** [comment]
> 

updated and pushed @mk-sada

**Comment by Mubashir-sadaindia** [comment]
> Unit tests are failing. Function signature mismatch. Fix please.
> 
> ```
> FAIL src/app/content-management/services/content-upload.service.spec.ts
>   ● Test suite failed to run
> 
>     apps/toboggan-app/src/app/content-management/services/content-upload.service.spec.ts:88:15 - error TS2554: Expected 3 arguments, but got 2.
> 
>     88       service.uploadMadCapFile(uuid, file).subscribe((res) => {
>                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>       apps/toboggan-app/src/app/content-management/services/content-upload.service.ts:47:50
>         47   uploadMadCapFile(uuid: string, isSrl: boolean, content_file: FormData) {
>                                                             ~~~~~~~~~~~~~~~~~~~~~~
>         An argument for 'content_file' was not provided.
> ```

Updated and pushed @mk-sada

**Review by mk-sada — APPROVED** [review]

**Pull request merged**
